async page => {
  const report = {};
  await page.setViewportSize({ width: 1440, height: 1080 });
  if (await page.getByRole('button', { name: 'Pause simulation', exact: true }).count()) await page.getByRole('button', { name: 'Pause simulation', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('run-state').textContent.includes('Paused'));
  await page.getByRole('button', { name: '02 A dimensional cascade', exact: false }).click();
  await page.waitForFunction(() => window.__labState?.time === 0 && window.__labState.options.biasB === .32);
  await page.getByRole('button', { name: 'Run simulation', exact: true }).click();
  await page.waitForFunction(() => window.__labState?.time >= 4, { timeout: 20000 });
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('run-state').textContent.includes('Paused'));
  report.cascade = await page.evaluate(() => ({ time: __labState.time, fractions: __labState.worlds.map(w => w.fraction), sites: __labState.worlds.map(w => w.nodes), live: __labState.particles.length, total: __labState.total }));
  await page.screenshot({ path: 'output/playwright/cascade-desktop.png' });
  await page.getByRole('button', { name: '03 A hole in one world', exact: false }).click();
  await page.waitForFunction(() => window.__labState?.time === 0 && window.__labState.options.holes === 'a');
  await page.getByRole('button', { name: 'Run simulation', exact: true }).click();
  await page.waitForFunction(() => window.__labState?.time >= 5, { timeout: 20000 });
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('run-state').textContent.includes('Paused'));
  report.closedHorizon = await page.evaluate(() => ({ time: __labState.time, captures: __labState.absorbed, transfers: __labState.transfers, live: __labState.particles.length, total: __labState.total }));
  await page.getByRole('button', { name: 'Worlds are separated Connect', exact: false }).click();
  await page.getByRole('button', { name: 'Launch matter & light', exact: false }).click();
  await page.getByRole('button', { name: 'Run simulation', exact: true }).click();
  await page.waitForFunction(() => window.__labState?.time >= 10, { timeout: 20000 });
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('run-state').textContent.includes('Paused'));
  report.openHorizon = await page.evaluate(() => ({ captures: __labState.absorbed, transfers: __labState.transfers, fromAInB: __labState.particles.filter(p => p.origin === 0 && p.world === 1).length, live: __labState.particles.length, total: __labState.total }));
  await page.screenshot({ path: 'output/playwright/horizon-desktop.png' });
  await page.getByRole('button', { name: '04 A curved neighbour', exact: false }).click();
  await page.waitForFunction(() => window.__labState?.worlds[1].geometry === 'torus' && window.__labState?.time === 0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'output/playwright/curved-mobile.png' });
  report.mobile = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, geometry: __labState.worlds[1].geometry, dim: __labState.worlds[1].dim, loadingHidden: document.getElementById('loading').hidden, errorHidden: document.getElementById('error').hidden }));
  await page.getByRole('button', { name: 'Model & sources', exact: false }).click();
  report.dialog = await page.getByRole('dialog').isVisible();
  await page.screenshot({ path: 'output/playwright/model-mobile.png' });
  await page.getByRole('button', { name: 'Close model explanation' }).click();
  await page.getByLabel('Choose experiment').selectOption('contact');
  await page.waitForFunction(() => window.__labState?.worlds[1].dim === 4);
  await page.screenshot({ path: 'output/playwright/contact-mobile.png' });
  return report;
}
